name: CI

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  test:
    # needed to allow julia-actions/cache to delete old caches that it has created
    permissions:
      actions: write
      contents: read
    
    runs-on: ubuntu-latest
    #runs-on: ${{ matrix.os }}
    #strategy:
    #  matrix:
    #    # test on a subset of possible platforms
    #    include:
    #      - version: '1'
    #        os: ubuntu-latest
    #        arch: x64
    #    #  - version: '1'
    #    #    os: ubuntu-latest
    #    #    arch: x86

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
        #  version: ${{ matrix.version }}
        #  arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      
      # TODO: julia-actions/julia-buildpkg@v1 and julia-actions/julia-runtest@v1
      # do not seem to work for unregistered packages(?)
      # and package root is a subfolder
      
      # install step as for building docs (below) is not needed here
      # since Pkg.test() takes care of this already.
      # Note that we need to tell Pkg explicitly to collect coverage data
      # (this would be done automatically in julia-actions/julia-runtest)
      - name: Install dependencies and run tests
        shell: julia --color=yes --project=. {0}
        run: |
          using Pkg
          Pkg.test("Spindles"; coverage=true)
        working-directory: ./Spindles
        
      # convert Julia coverage files into an lcov file
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: Spindles/src,Spindles/ext  # !! no whitespace after comma here!!
      #- name: Preview coverage data
      #  run: cat lcov.info
      # generate a simple summary of the lcov file
      - name: Print code coverage report
        run: julia --color=yes -- .github/workflows/codecoverage.jl lcov.info
      
      ## upload to codecov
      #- uses: codecov/codecov-action@v5
      #  with:
      #    files: lcov.info

  docs:  # see https://documenter.juliadocs.org/stable/man/hosting/#GitHub-Actions
    # These permissions are needed to:
    # - Deploy the documentation: https://documenter.juliadocs.org/stable/man/hosting/#Permissions
    # - Delete old caches: https://github.com/julia-actions/cache#usage
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
      
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2
      - name: Install dependencies
        shell: julia --color=yes --project=docs {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
        working-directory: ./Spindles
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GKSwstype: "100"  # https://discourse.julialang.org/t/generation-of-documentation-fails-qt-qpa-xcb-could-not-connect-to-display/60988
        run: julia --color=yes --project=docs docs/make.jl
        working-directory: ./Spindles
